id: I09E2E8BF
ocr_import_info:
  timestamp: '2023-08-17T01:57:40.312390+00:00'
  batch_id: batch-26fb
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-08-17 02:24:56.520964+00:00
last_modified: 2023-08-17 02:24:56.520970+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W23423
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23423
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཤེས་རབ་འོད་ཟེར།
  languages:
  - bo
  author: འཕྲེང་པོ་གཏེར་སྟོན་ཤེས་རབ་འོད་ཟེར།
statistics:
  ocr_word_mean_confidence_index: 0.9495685345823456
  ocr_word_median_confidence_index: 0.9932442
bases:
  I1578:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1578
      total_pages: 538
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1578.txt
    statistics:
      ocr_word_median_confidence_index: 0.9932442
      ocr_word_mean_confidence_index: 0.9495685345823456
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
